server:
  port: 80
spring:
  redis:
    # redis的ip地址
    host: 120.27.247.183
    # redis的端口号
    port: 6379
    # redis的密码
    password:
    lettuce:
      pool:
        # 最大链接数
        max-active: 30
        # 链接池中最大空闲链接数
        max-idle: 15
        # 最大阻塞等待链接时长 默认不限制 -1
        max-wait: 2000
        # 最小空闲链接数
        min-idle: 10
      # 链接超时时长
      shutdown-timeout: 10000